"""file table

Revision ID: 343182255358
Revises: 
Create Date: 2018-04-09 15:52:56.415726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343182255358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('block_hash', sa.String(length=64), nullable=True),
    sa.Column('block_index', sa.Integer(), nullable=True),
    sa.Column('txn_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_file_hash'), 'file', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_file_hash'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
